### ISSUE TITLE
Avoid hardcoding values that are meant to be secret.

### ISSUE THREAD

**Issue by PaulFelge** [MantasMikal/gatsby-instagram#22]
Avoid hardcoding values that are meant to be secret. Found a hardcoded access_token in gatsby-config.js. 
[Gatsby environment-variables ](https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/)

The problem is that other developers copy your code and do the same mistake instead of getting used to use secrets ;-)

**Comment by MantasMikal** [comment]
Thanks for the tip! This is a throwaway account so I don't really care. Want this work out of the box
