### ISSUE TITLE
.mp4 format warn-error

### ISSUE THREAD

**Issue by Nor-Norit-Nor** [MantasMikal/gatsby-instagram#7]
Hello! I'm trying to add my instagram's feed to my page according to your code on this repository , but an error occurred with the .mp4 format files of the videos I have:

"warn You can't use childImageSharp together with 10603_34563580515_n.mp4 — use publicURL instead. The childImageSharp portion of the query in this file will return null"

And it doesn't work neither for the images on .jpg format.

Any ideas? I appreciate the help :)

**Comment by MantasMikal** [comment]
Hi @Nor-Norit-Nor 
I have addressed the problem in the latest plugin update. 
It should skip processing those videos now :)
